---
title: "Calculate correlation between mrna, mirna, and methylation expressions at any 2 differentiation states"
author: "Thanneer Perumal"
date: '`r date()`'
output: html_document
---
```{r knit2synapse, eval = FALSE, include=FALSE}
library(synapseClient)
library(knit2synapse)

synapseLogin()

knit2synapse::knitToFolderEntity(file = 'CalculateCoExp_Any2DiffState.Rmd',
                                 parentId = "syn5194922",
                                 entityName = 'Coexpression Between Different Assays At Any Two Differentiation Stage')
```

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
## It is assumed your working directory is where this file is

# Clear R console screen output
cat("\014")

# Load libraries
library(plyr)
library(dplyr)
library(data.table)
library(stringr)
library(tidyr)
library(reshape2)

library(matrixStats)
library(biomaRt)

library(knitr)
library(knit2synapse)
library(synapseClient)
library(rGithubClient) ## Needs the dev branch

library(doParallel)
registerDoParallel(40)

synapseLogin()

# Load required files
source('../R/lib/rownameToFirstColumn.R')

options(xtable.type="html")

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE)
```

```{r synapseStore.params, cache=FALSE}
parentId = "syn5194922"
SYNAPSE_STORE = T  
ALL_USED_IDs = c()

# Create folder to store results in synapse
ActivityName <- 'Calculate co-expression between assays'

ThisFileName <- 'CalculateCoExp_Any2DiffState.Rmd'

# Github link
ThisRepo <- getRepo(repository = "th1vairam/pcbc_c4_analysis", 
                    ref="branch", 
                    refName='discordant_anal')

ThisFile <- getPermlink(repository = ThisRepo,
                        repositoryPath=paste0('code/Rmd/', ThisFileName))    

# Populate wiki with results
CODE <- Folder(name = 'Coexpression Between Different Assays At Any Two Differentiation Stage', parentId = parentId)
CODE <- synStore(CODE)
```

```{r fxns}
downloadFile <- function(id){
  tmp = fread(synGet(id)@filePath, data.table=F, header=T)
}

# Function to calculate co-expression
calculateCor <- function(metaData, omics1Mat, omics2Mat, Interactions){
  compName = paste(unique(metaData$Diffname_short), collapse = '_vs_')
  
  ## For group1
  omics1Mat = omics1Mat[,metaData$biologicalSampleName]
  omics2Mat = omics2Mat[,metaData$biologicalSampleName]
  
  # Calcualte correlation between features at group1
  correlation = WGCNA::bicor(t(omics1Mat[as.character(Interactions[1]),]),
                             t(omics2Mat[as.character(Interactions[2]),]),
                             use = "pairwise.complete.obs")
  # correlation = cor(t(omics1Mat[as.character(Interactions[1]),]), 
  #                   t(omics2Mat[as.character(Interactions[2]),]), 
  #                   use = "pairwise.complete.obs")
  return(correlation)
}
```

### Get expression matrices and metadata
#### Get counts matrices
```{r download.counts}
counts_id = c(mrna = 'syn5011095', mirna = 'syn5014454', methyl = 'syn4487642')
ALL_USED_IDs = c(ALL_USED_IDs, counts_id)

counts = lapply(counts_id, function(id){
  Counts = downloadFile(id)
  
  row.names(Counts) = Counts[,1]
  # colnames(Counts) = gsub('-','.',colnames(Counts))
  Counts = as.matrix(Counts[,-(1)])
})

#### Get splicing matrices
spliceJunction_id = 'syn5048714'
ALL_USED_IDs = c(ALL_USED_IDs, spliceJunction = spliceJunction_id)

PSI = downloadFile(spliceJunction_id)
rownames(PSI) = PSI$`Minor-Isoform`
PSI = PSI[,-c(1,227:236)]

counts = c(counts, list(spliceJunction = data.matrix(PSI)))
counts = sapply(counts, function(x){x = x[1:100,]})
```
#### Get metadata matrices
```{r download.metadata}
#### Get metadata matrices
metadata_id = c(mrna = 'syn3156503', mirna = 'syn3219876', 
                methyl = 'syn3156828', spliceJunction = 'syn3156503')
ALL_USED_IDs = c(ALL_USED_IDs, metadata_id)

# Get metadata from synapse
metadata = lapply(metadata_id, function(id){
  # Get metadata from synapse tables
  MetaData <- synTableQuery(sprintf('SELECT * FROM %s', id))@values
  MetaData[MetaData == 'N/A'] = NA
  
  # Replace all special characters with blank
  myFix <- function(x) str_replace_all(x, '[^[:alnum:]]', '')
  MetaData <- MetaData %>%
    dplyr::mutate_each(funs(myFix), -UID, -C4_Cell_Line_ID, -biologicalSampleName,
                       -public, -pass_qc, -exclude) # fix them but don't touch some columns
  
  # MetaData$UID = gsub('-','.',MetaData$UID)
  rownames(MetaData) = MetaData$UID
  return(MetaData)
})

# Arrange metadata rows wrt counts columns
metadata = mapply(function(Counts, MetaData){
  ind = intersect(colnames(Counts),rownames(MetaData))
  MetaData = MetaData[ind,]
  MetaData = MetaData[colnames(Counts),]
}, counts, metadata, SIMPLIFY = F)
```

### Download all interactions from synapse
```{r all.interactions}
ALL_USED_IDs = c(ALL_USED_IDs, all.interactions = 'syn5643683')
allInteractions = downloadFile('syn5643683') %>%
  dplyr::mutate(Assay = paste(feature.assay,target.assay,sep = '_'))

# Get all possible interactions (that are meaningful)
mrna.mrna = combn(rownames(counts$mrna), 2) %>% t %>% 
  data.frame %>% setnames(c('X1','X2'), c('feature', 'target')) %>%
  dplyr::mutate(Assay = "mrna_mrna", feature.assay = "mrna", target.assay = "mrna", dataSource = "all")
mirna.mrna = expand.grid(rownames(counts$mirna), rownames(counts$mrna)) %>%
  setnames(c('Var1','Var2'), c('feature', 'target')) %>%
  dplyr::mutate(Assay = "mirna_mrna", feature.assay = "mirna", target.assay = "mrna", dataSource = "all")
methyl.mrna = expand.grid(rownames(counts$methyl), rownames(counts$mrna)) %>%
  setnames(c('Var1','Var2'), c('feature', 'target')) %>%
  dplyr::mutate(Assay = "methyl_mrna", feature.assay = "methyl", target.assay = "mrna", dataSource = "all")
methyl.mirna = expand.grid(rownames(counts$methyl), rownames(counts$mirna)) %>%
  setnames(c('Var1','Var2'), c('feature', 'target')) %>%
  dplyr::mutate(Assay = "methyl_mirna", feature.assay = "methyl", target.assay = "mirna", dataSource = "all")
mrna.splicing = expand.grid(rownames(counts$methyl), rownames(counts$mirna)) %>%
  setnames(c('Var1','Var2'), c('feature', 'target')) %>%
  dplyr::mutate(Assay = "methyl_mirna", feature.assay = "methyl", target.assay = "mirna", dataSource = "all")

```

#### Coallate counts and metadata
Combine samples to unique biological sample name (take median values for replicates)
```{r coallateData}
counts.metadata = llply(unique(allInteractions$Assay),
                        .fun = function(assay, Counts, MetaData){
                          feature.assay = str_split(assay, '\\_')[[1]][1]
                          target.assay = str_split(assay, '\\_')[[1]][2]
                          
                          # Match up biological sample between assays
                          biosampleInBoth <- intersect(MetaData[[feature.assay]]$biologicalSampleName, 
                                                       MetaData[[target.assay]]$biologicalSampleName)
                          # Filter metadata
                          feature.metadata <- MetaData[[feature.assay]] %>%
                            filter(biologicalSampleName %in% biosampleInBoth)
                          
                          target.metadata <- MetaData[[target.assay]] %>%
                            filter(biologicalSampleName %in% biosampleInBoth)
                          
                          # Take the median across multiple biological samples per feature
                          feature.median <- Counts[[feature.assay]] %>%
                            rownameToFirstColumn('feature') %>%
                            dplyr::select(feature, one_of(feature.metadata$UID)) %>%
                            melt %>%
                            dplyr::rename(UID = variable, expression = value) %>%
                            left_join(feature.metadata %>% dplyr::select(UID, biologicalSampleName)) %>%
                            group_by(feature, biologicalSampleName) %>% 
                            summarize(median_expression=median(expression)) %>% 
                            dcast(feature ~ biologicalSampleName)
                          
                          rownames(feature.median) = feature.median$feature
                          feature.median$feature = NULL
                          
                          target.median <- Counts[[target.assay]] %>%
                            rownameToFirstColumn('feature') %>%
                            dplyr::select(feature, one_of(target.metadata$UID)) %>%
                            melt %>%
                            dplyr::rename(UID = variable, expression = value) %>%
                            left_join(target.metadata %>% dplyr::select(UID, biologicalSampleName)) %>%
                            group_by(feature, biologicalSampleName) %>% 
                            summarize(median_expression=median(expression)) %>% 
                            dcast(feature ~ biologicalSampleName)
                          
                          rownames(target.median) = target.median$feature
                          target.median$feature = NULL
                          
                          # Get unique metadata
                          unique.metadata <- feature.metadata %>%
                            dplyr::select(biologicalSampleName, Diffname_short, Originating_Lab, Cell_Type,
                                          Cell_Line_Type, Cell_Line_of_Origin, Tissue_of_Origin,
                                          Reprogramming_Gene_Combination, Culture_Conditions,
                                          Cell_Type_of_Origin_Level2, Reprogramming_Vector_Type_Level2) %>%
                            dplyr::filter(biologicalSampleName %in% biosampleInBoth) %>%
                            dplyr::mutate(Diffname_short = gsub('-','',Diffname_short)) %>% 
                            unique
                          
                          feature.median = feature.median[,unique.metadata$biologicalSampleName]
                          target.median = target.median[,unique.metadata$biologicalSampleName]
                          
                          return(list(metdata = unique.metadata, 
                                      feature = feature.median, 
                                      target = target.median))
                          },
                        counts, metadata,
                        .progress = 'text',
                        .parallel = T)
names(counts.metadata) = unique(allInteractions$Assay)
```

#### Calculate co-expression in all five different categories of interactions at any 2 diffstate
```{r combine.samples}
correlation = ddply(allInteractions, 
            .(feature, target, feature.assay, target.assay, dataSource, Assay), 
            .fun = function(interaction, Counts.Metadata){
              assay = interaction$Assay
              feature.assay = unique(interaction$feature.assay)
              target.assay = unique(interaction$target.assay)
              
              # Extract feature median value
              feature.median = Counts.Metadata[[assay]]$feature[interaction$feature,]
              
              # Extract target median value
              target.median = Counts.Metadata[[assay]]$target[interaction$target,]
              
              # Extract metadata
              unique.metadata = Counts.Metadata[[assay]]$metdata
              
              # Combine metadata for all combinations of any 2 diffstate
              all.combination = combn(sort(unique(unique.metadata$Diffname_short)),2)
              
              # Calculate co-expression
              correlation = apply(all.combination, 2, function(x){
                calculateCor(unique.metadata %>% dplyr::filter(Diffname_short %in% x),
                             feature.median, target.median, interaction)
              }) %>% as.data.frame %>% t
              colnames(correlation) = apply(all.combination,2,paste, collapse = '_vs_')
              
              return(correlation)
              }, counts.metadata,
            .progress = 'text',
            .parallel = T)
```

```{r synapse.store}
# Store metadata in synapse
write.table(correlation, file = 'correlationDiffComparison.tsv', sep = '\t', quote=F, row.names=F)
obj = File('correlationDiffComparison.tsv', name = 'Correaltion coefficients', parentId = CODE$properties$id)
obj = synStore(obj, used = as.character(ALL_USED_IDs), executed = ThisFile, activityName = ActivityName)
```

### Source Code
[Source R Markdown](`r ThisFile`)